### ISSUE TITLE
tikz package'i kasutamine tekitab tühja lehe peale kinnituslehte.

### ISSUE THREAD

**Issue by marko213** [prandla/trkut#1]
Minimaalne näide - põhifailile lisada `\usepackage{tikz}`  ning enne dokumendi lõppu `\kinnitusleht`:

```
\documentclass{trkut}
\usepackage{tikz}

\begin{document}

\kinnitusleht

\end{document}
```

**Comment by marko213** [comment]
Võimalik lahendus - eemaldada (välja kommenteerida) failis trkut.cls rida

```
\setlength{\topskip}{0 cm}
```

`kinnitusleht` definitsiooni all.

**Comment by trillllian** [comment]
fixed in 68c325fb8fd09c167bb43e87ad1df4668a710f39
