### ISSUE TITLE
Valemid peaksid olema vasakule joondatud

### ISSUE THREAD

**Issue by marko213** [prandla/trkut#2]
Hetkel on valemid joondatud keskele. Vormistusjuhistest "Võrdsust ja võrratust väljendavad keerukamad valemid kirjutatakse omaette reale ja joondatakse vasakule."

Võimalik lahendus oleks asendada `\documentclass{trkut}` `\documentclass[fleqn]{trkut}`-ga, kuid ilmselt saab seda kuidagi .cls failist ka teha.

**Comment by trillllian** [comment]
ma ei saanud seda lihtsalt `$$`'ga tööle niiet panin readme'sse et tuleb selle asemel `equation*` kasutada, aga muidu fixed nüüd
